using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace mosair.Services
{
    public class Loc : INotifyPropertyChanged
    {
        public static Loc Instance { get; } = new();
        public static bool IsMac { get; } = RuntimeInformation.IsOSPlatform(OSPlatform.OSX);
        private static readonly string Mod = IsMac ? "⌘" : "Ctrl";

        public string KeyMod => Mod;
        public string KeyModI => $"{Mod}+I";
        public string KeyModO => $"{Mod}+O";
        public string KeyModS => $"{Mod}+S";
        public string KeyModShiftS => IsMac ? "⌘+⇧+S" : "Ctrl+Shift+S";
        public string KeyModE => $"{Mod}+E";
        public string KeyModM => $"{Mod}+M";
        public string KeyMod0 => $"{Mod}+0";
        public string KeyModZ => $"{Mod}+Z";
        public string KeyModY => $"{Mod}+Y";

        private string _lang = "tr";

        public string this[string key] =>
            (_lang == "en" ? En : Tr).TryGetValue(key, out var v) ? v : key;

        public static string Get(string key) =>
            Instance[key];

        public static string Fmt(string key, params object[] args) =>
            string.Format(Get(key), args);

        public bool IsTr => _lang == "tr";
        public bool IsEn => _lang == "en";

        public string Lang
        {
            get => _lang;
            set
            {
                if (_lang == value) return;
                _lang = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(""));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Lang"));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("IsTr"));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("IsEn"));
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;

        // ─── TÜRKÇE ───
        private static readonly Dictionary<string, string> Tr = new()
        {
            // Menu
            ["MenuFile"] = "Dosya",
            ["MenuLoadImage"] = "Gorsel Yukle",
            ["MenuOpenProject"] = "Proje Ac",
            ["MenuSave"] = "Proje Kaydet",
            ["MenuSaveAs"] = "Proje Farkli Kaydet",
            ["MenuExport"] = "mosairEXPORT",
            ["MenuExportAs"] = "mosairEXPORT As",
            ["MenuEdit"] = "Duzenle",
            ["MenuSelectAll"] = "Tum Renkleri Sec",
            ["MenuDeselectAll"] = "Tum Renkleri Kaldir",
            ["MenuView"] = "Gorunum",
            ["MenuFitToScreen"] = "Ekrana Sigdir",
            ["MenuPropertiesPanel"] = "Özellikler Paneli",
            ["MenuAdjustPanel"] = "Görsel Ayarları",
            ["AdjTitle"] = "GÖRSEL AYARLARI",
            ["AdjTabLight"] = "Işık",
            ["AdjTabColor"] = "Ton/Doygunluk",
            ["AdjLiveMos"] = "Anlık Mos",
            ["TipAdjLiveMos"] = "Açıkken her ayar değişikliğinden sonra Mos kendiliğinden yapılır ve mozaik hemen güncellenir. Kapalıyken değişiklik yapınca ekranda ayarlanmış görsel görünür; mozaik için Mos'a basın.",
            ["AdjExposure"] = "Pozlama",
            ["AdjHighlights"] = "Parlak Alanlar",
            ["AdjShadows"] = "Gölgeler",
            ["AdjWhites"] = "Beyazlar",
            ["AdjBlacks"] = "Siyahlar",
            ["AdjHue"] = "Ton",
            ["AdjLightness"] = "Açıklık",
            ["AdjColorize"] = "Renklendir",
            ["TipAdjColorize"] = "Görselin tamamını tek bir tona boyar; Ton, Doygunluk ve Açıklık bu tonu ayarlar.",
            ["AdjRange0"] = "Ana (tüm renkler)",
            ["AdjRange1"] = "Kırmızılar",
            ["AdjRange2"] = "Sarılar",
            ["AdjRange3"] = "Yeşiller",
            ["AdjRange4"] = "Camgöbekleri",
            ["AdjRange5"] = "Maviler",
            ["AdjRange6"] = "Eflatunlar",
            ["AdjHint"] = "Sağ tık: sıfırla · Shift + sürükle: ince ayar · Tekerlek: ±1 · Değer kutusu: Enter",
            ["AdjBrightness"] = "Parlaklık",
            ["AdjContrast"] = "Kontrast",
            ["AdjSaturation"] = "Doygunluk",
            ["AdjGamma"] = "Gama",
            ["AdjReset"] = "Sıfırla",
            ["AdjNeedsMos"] = "Görsel ayarları değişti; mozaiği güncellemek için Mos'a basın.",
            ["TipAdjust"] = "Yüklenen görselin parlaklık, kontrast, doygunluk ve gama ayarları. Mos ayarlanmış görselden yapılır; dosyanın kendisi değişmez, ayarlar projeyle kaydedilir.",
            ["TipAdjSlider"] = "Sağ tıklayınca sıfırlanır",
            ["TipAdjustShow"] = "Görsel ayarlarını göster",
            ["MenuSmoothMouse"] = "Yumuşak Fare Hareketi",
            ["MenuTheme"] = "Tema",
            ["MenuLightTheme"] = "Açık Tema",
            ["ThemeLapis"] = "Lapis",
            ["ThemePastel"] = "Adaçayı ve Lavanta",
            ["ThemeGraphite"] = "Grafit ve Petrol",
            ["ThemeTravertine"] = "Traverten",
            ["ThemeInk"] = "Mürekkep ve Leylak",
            ["MenuWatchImages"] = "Yeni Görselleri Bildir",
            ["ToastNewDownload"] = "İNDİRİLENLER'E YENİ GÖRSEL",
            ["ToastNewDesktop"] = "MASAÜSTÜNE YENİ GÖRSEL",
            ["ToastQuestion"] = "mosair'de açılsın mı?",
            ["ToastExported"] = "DIŞA AKTARILDI",
            ["ToastScreenshotSaved"] = "EKRAN GÖRÜNTÜSÜ KAYDEDİLDİ",
            ["ToastProjectSaved"] = "PROJE KAYDEDİLDİ",
            ["ToastOpenFile"] = "Aç",
            ["ToastShowFolder"] = "Klasörü aç",
            ["ToastOpen"] = "Aç",
            ["ToastDismiss"] = "Kapat",
            ["ToastSeconds"] = "{0} sn",
            ["StatusToastBusy"] = "Bir işlem sürüyor; bitince açabilirsiniz.",
            ["StatusSavingProject"] = "Proje kaydediliyor: {0}",
            ["StatusOpeningProject"] = "Proje açılıyor: {0}",
            ["MenuTools"] = "Araclar",
            ["MenuMosaicize"] = "Mozaiklestir",
            ["MenuPixelEdit"] = "Piksel Duzenle",
            ["MenuShowGrid"] = "Izgara Goster",
            ["MenuGridColor"] = "Izgara Rengi",
            ["MenuInterp"] = "Interpolasyon Yontemi",
            ["MenuOptimum"] = "Optimum Tas Sayisi",
            ["MenuStoneCount"] = "Tas Sayisi",
            ["MenuStonesSuggested"] = "Onerilen Degere Don",
            ["MenuStonesMore"] = "Bir Tas Artir",
            ["MenuStonesLess"] = "Bir Tas Azalt",
            ["MenuStock"] = "Stok",
            ["MenuStockOpen"] = "Stok Tablosunu Ac",
            ["MenuStockFetch"] = "Stok Cek",
            ["MenuStockCheck"] = "Stok Kontrol",
            ["MenuStockAdd"] = "Stok Ekle",
            ["MenuHelp"] = "Yardim",
            ["MenuUserGuide"] = "Kullanim Kilavuzu",

            // Toolbar tooltips
            ["TipLoadImage"] = "Gorsel Yukle",
            ["TipOpenProject"] = "Proje Ac (.mos)",
            ["TipSave"] = "Proje Kaydet",
            ["TipMosaicize"] = "Mozaiklestir",
            ["TipPixelEdit"] = "Piksel Duzenle (Orta Tus)\n1) Kaynak renk sec\n2) Hedef piksele uygula",
            ["TipSaveAs"] = "Proje Farkli Kaydet",
            ["TipExport"] = "Dışa aktar: mosairEXPORT / mosairEXPORT As, görüntü kalitesi seçerek (boyut bilgisiyle). Sağ tık: klasörü aç",
            ["TipFit"] = "Ekrana Sigdir",
            ["TipGrid"] = "Izgara Goster/Gizle",
            ["TipInterp"] = "Interpolasyon Yontemi",
            ["TipLanguage"] = "Dil",
            ["TipTheme"] = "Tema Degistir",

            // Buttons
            ["BtnSelectAll"] = "Tum Renkleri Sec",
            ["BtnDeselectAll"] = "Tum Renkleri Kaldir",

            // Column headers
            ["ColCatalog"] = "Katalog Renk",
            ["ColMatch"] = "Eslesme",
            ["ColAssigned"] = "Atanan Renk",

            // Left panel
            ["LblGrid"] = "Grid",
            ["LblGridColor"] = "Grid Rengi",
            ["LblInterp"] = "Interp",
            ["LblOptimum"] = "Optimum",
            ["TipOptimum"] = "Optimum taş sayısını otomatik bul",
            ["TipOptimalSlider"] = "Taş çeşidi sayısı (sağ tık: önerilen sayı)",

            // Google Sheet stock
            ["TipStockSheet"] = "Stok tablosunu tarayıcıda aç (yanındaki ok: tabloyu aç / stok tablosu ayarları)",
            ["TipStockSheetMenu"] = "Stok tablosu: aç veya ayarla",
            ["TipStockFetch"] = "Stok çek: Google Sheet'ten stoğu oku, stoğu biten taşları devre dışı bırak (yanındaki ok: yalnızca kırmızıyla işaretle)",
            ["TipStockFetchMenu"] = "Stok çek seçenekleri",
            ["MenuStockFetchDisable"] = "Stoğu olmayanları devre dışı bırak",
            ["MenuStockFetchMark"] = "Stoğu olmayanları kırmızıyla işaretle",
            ["TipStockCheck"] = "Stok kontrol: bu mozaiğin taş adetlerini tabloya yaz, stoğu yetmeyen taşları işaretle",
            ["TipStockClear"] = "Stok temizle: bu mozaiğin sütununu temizle (sağ tık: tüm mozaik sütunları)",
            ["TipStockAdd"] = "Stok ekle: Tahmini Kalan'ı Bizdeki'ye taşı, mozaik sütunlarını temizle",
            ["MenuStockSettings"] = "Stok Ayarları...",
            ["MenuStockClearOne"] = "Bu mozaiğin sütununu temizle",
            ["MenuStockClearAll"] = "Tüm mozaik sütunlarını temizle",
            ["StockTitle"] = "Stok",
            ["StockNotConfigured"] = "Stok tablosu ayarlı değil. Tablo butonunun yanındaki oktan (veya sağ tıklayarak) Stok Ayarları'nı açıp Sheet ID ve Script URL girin.",
            ["StockErrFmt"] = "Stok işlemi başarısız:\n{0}",
            ["StockErrColumns"] = "'{0}' sütunu bulunamadı. Bulunan başlıklar: {1}",
            ["StockErrEmpty"] = "Tablo boş döndü.",
            ["StockErrDeploy"] = "Script URL geçersiz veya yayın ayarları hatalı. Apps Script → Manage deployments → Access: Anyone olmalı.",
            ["StockNoProject"] = "Proje adı bulunamadı. Önce bir görsel yükleyin.",
            ["StockNoMosaic"] = "Taş verisi yok. Önce Mos çalıştırın.",
            ["StockFetched"] = "Stok çekildi: {0} taş okundu, {1} taş devre dışı",
            ["StockFetchedMarked"] = "Stok çekildi: {0} taş okundu, {1} taşın stoğu yok (kırmızı nokta, seçim değişmedi)",
            ["StockLoadedOnStart"] = "Stok bilgisi yüklendi: {0} taş (katalog ipucunda kg)",
            ["StockLoadOnStartFailed"] = "Stok bilgisi yüklenemedi: {0}",
            ["StockCheckOk"] = "Stok kontrol ({0}): tüm taşlar için stok yeterli",
            ["StockCheckShort"] = "Stok kontrol ({0}): {1} taşın stoğu yetersiz (kırmızı nokta)",
            ["StockKgLeft"] = "kaldı",
            ["LblStockAware"] = "Stoğa göre",
            ["MenuStockAware"] = "Stoğa Göre Ayarla",
            ["TipStockAware"] = "Stoğa göre: Açıkken Mos (Optimum ya da normal) yalnızca stokta olan taşlarla yapılır. Stoğu yetmeyen taş elde olduğu kadar kullanılır, kalan yer renkçe en yakın stoklu taşla doldurulur. Stok, uygulama açılırken ve her görsel ya da proje yüklendiğinde tablodan okunur: Bizdeki (kg) eksi diğer mozaiklerin ayırdığı miktar. 1 taş = 3,3 g. Stok Kontrol son adetleri tabloya yazar.",
            ["StockAwareNoStock"] = "Stok tablodan okunamadı; Mos stoğa bakmadan yapıldı.",
            ["StockAwareTitle"] = "Stoğa Göre",
            ["StockAwareEditsConfirm"] = "Stoğa göre düzeltme {0} piksel düzenlemesini sıfırlayacak. Devam edilsin mi?",
            ["StockAwareWritten"] = "düzeltilmiş adetler tabloya yazıldı",
            ["StockCountsWritten"] = "adetler tabloya yazıldı",
            ["StockAwareRecheck"] = "taş sayısı değişti, tablo için Stok Kontrol'ü tekrarlayın",
            ["StockAwareSmall"] = "{0} taştan az kullanıldığı için çıkarılan: {1}",
            ["StockAwareReadFailed"] = "Stok okunamadı, stoğa göre düzeltme yapılmadı: {0}",
            ["StockAwareNeedsMos"] = "Stoğa göre düzeltme için önce bu görselle Mos yapın (açılan projelerde çalışmaz).",
            ["StockAwareCannotFix"] = "Bazı pikseller bir katalog taşıyla kesin eşleştirilemediği için stoğa göre düzeltme yapılmadı (katalog dışı ya da aynı renkte iki taş).",
            ["StockAwareOk"] = "Stok yeterli, mozaik değişmedi",
            ["StockAwareChanged"] = "Stoğa göre: {0} taş türünden {1} taş yer değiştirdi",
            ["StockAwareMove"] = "{0} → {1}: {2} taş ({3} kg)",
            ["StockAwareAdded"] = "Yeni eklenen taş türü: {0}",
            ["StockAwareLevel1"] = "Yakın renkte stok yetmediği için benzerlik sınırı 2 katına genişletildi.",
            ["StockAwareLevel2"] = "Yakın renkte stok yetmediği için benzerlik sınırı 4 katına genişletildi.",
            ["StockAwareLevel3"] = "Yakın renkte stok yetmediği için stoğu olan herhangi bir taş kullanıldı.",
            ["StockAwareLevel4"] = "Stok, yeni taş türü sınırı aşılarak karşılandı.",
            ["StockAwareShort"] = "Stoğu hâlâ yetmeyen: {0}",
            ["StockAwareUnknown"] = "Tabloda stok kaydı olmayan, kontrol edilemeyen taşlar: {0}",
            ["StockAwareShortCount"] = "stoğu hâlâ yetmeyen {0} taş türü",
            ["StockAwareUnknownCount"] = "tabloda kaydı olmayan {0} taş türü",
            ["StockAwareSeeWindow"] = "ayrıntılar açılan pencerede",
            ["StockAwareSeeTooltip"] = "ayrıntılar Stoğa göre ipucunda",
            ["StockClearTitle"] = "Stok Temizle",
            ["StockClearOneConfirm"] = "'{0}' mozaiğinin sütunu temizlenecek ve başlığı mozaikX olarak sıfırlanacak.\n\nEmin misiniz?",
            ["StockClearedOne"] = "'{0}' sütunu temizlendi",
            ["StockClearAllTitle"] = "Tümünü Temizle",
            ["StockClearAllConfirm"] = "Tüm mozaik sütunları temizlenecek ve başlıkları sıfırlanacak.\n\nEmin misiniz?",
            ["StockClearedAll"] = "Tüm mozaik sütunları temizlendi",
            ["StockAddTitle"] = "Stok Ekle",
            ["StockAddConfirm"] = "Tahmini Kalan değerleri Bizdeki sütununa taşınacak, sonra tüm mozaik sütunları temizlenecek.\n\nEmin misiniz?",
            ["StockAdded"] = "Stok eklendi",
            ["StockSettingsTitle"] = "Stok Tablosu Ayarları",
            ["StockSheetIdLabel"] = "Google Sheet ID",
            ["StockScriptUrlLabel"] = "Apps Script URL",
            ["StockSheetIdHint"] = "Stok tablosunu tarayıcıda açın; adres çubuğundaki bağlantıda /d/ ile /edit arasındaki kısım Sheet ID'dir. Bağlantının tamamını da yapıştırabilirsiniz, ID kaydederken otomatik ayrılır. Stok Çek ve Stok Kontrol bu tabloyu okur.",
            ["StockScriptUrlHint"] = "Tabloda Uzantılar → Apps Komut Dosyası'nı açın, ardından Dağıt → Dağıtımları yönet'e gidin ve Web uygulaması URL'sini kopyalayın. Adres /exec ile bitmelidir. Stok Kontrol, Stok Sil ve Stok Ekle tabloya bu adres üzerinden yazar.",
            ["StockRequirementsTitle"] = "Doğru çalışması için",
            ["StockRequirements"] = "• Tablo, \"Bağlantıya sahip olan herkes\" için en az Görüntüleyen erişimiyle paylaşılmış olmalıdır.\n• İlk satırda mos, Bizdeki (kg) ve Tahmini Kalan başlıklı sütunlar bulunmalıdır.\n• Web uygulaması \"Erişimi olanlar: Herkes\" ayarıyla dağıtılmış olmalıdır. Betik tabloya önceden kurulmuş olmalıdır; bu adımları genellikle tablo sahibi yapar.\n• Tabloyu değiştiren işlemleri denemek için önce tablonun bir kopyasıyla çalışmanız önerilir.",
            ["StockSettingsNote"] = "Bu bilgiler sadece bu bilgisayarda saklanır. Script URL'yi bilen herkes tabloya yazabilir; yalnızca güvendiğiniz kişilerle paylaşın.",
            ["StockSettingsSaved"] = "Stok ayarları kaydedildi",
            ["DlgYes"] = "Evet",
            ["DlgNo"] = "Hayır",
            ["DlgSave"] = "Kaydet",
            ["DlgCancel"] = "İptal",

            // Properties
            ["PropTitle"] = "Properties",
            ["PropColor"] = "RENK",
            ["PropTexture"] = "DOKU",
            ["PropVariants"] = "VARYANTLAR",
            ["PropRgb"] = "RGB",
            ["PropCoordinate"] = "KOORDİNAT",
            ["PropPixel"] = "Piksel",
            ["PropMold"] = "Kalıp",
            ["PropEditing"] = "DÜZENLEME",
            ["PropImage"] = "GÖRSEL",
            ["PropDetails"] = "AYRINTILAR",
            ["PropResolution"] = "Çözünürlük",
            ["PropMegapixels"] = "Megapiksel",
            ["PropAspect"] = "En-boy oranı",
            ["PropFileSize"] = "Dosya boyutu",
            ["PropModified"] = "Değiştirilme",
            ["PropStoneHint"] = "Taş bilgileri için mozaikte bir taşa tıklayın.",
            ["PropNoImage"] = "Görsel yüklendiğinde bilgileri burada görünür.",
            ["PropImageMissing"] = "Görsel dosyası bulunamadı",
            ["TipPanelHide"] = "Paneli gizle (F4)",
            ["TipPanelShow"] = "Özellikler panelini göster (F4)",
            ["TipClearSelection"] = "Görsel bilgilerine dön",
            ["PropUndoRedo"] = $"{Mod}+Z Geri Al  {Mod}+Y Yinele",

            // Warning
            ["WarnOk"] = "Anladım",

            // Status (format strings)
            ["StatusReady"] = "Hazir",
            ["StatusImageLoaded"] = "Gorsel yuklendi",
            ["StatusStarting"] = "Mozaiklestirme baslatildi...",
            ["StatusActiveColors"] = "Aktif renk: {0}/{1}",
            ["StatusCalculated"] = "rgbM={0} hesaplandi, isleniyor...",
            ["StatusCompleted"] = "Tamamlandi — {0} renk, {1}s",
            ["StatusUsedColors"] = "{0} renk arasindan {1} renk kullanildi",
            ["StatusSaved"] = "Kaydedildi: {0}",
            ["StatusExporting"] = "Disa aktariliyor: {0}...",
            ["StatusExportingPct"] = "Dışa aktarılıyor: {0} — %{1}",
            ["BtnCancel"] = "İptal",
            ["MenuDrive"] = "Google Drive",
            ["MenuDriveSave"] = "Drive'a Kaydet",
            ["MenuDriveOpen"] = "Drive'dan Aç...",
            ["MenuDriveSettings"] = "Drive Klasörü Ayarları...",
            ["TipDrive"] = "Google Drive: projeyi Drive klasörüne kaydet (ok: Drive'dan aç, klasör ayarları)",
            ["AlertDriveTitle"] = "Google Drive",
            ["DriveSettingsTitle"] = "Google Drive Ayarları",
            ["DriveFolderLabel"] = "Drive klasörü bağlantısı",
            ["DriveFolderHint"] = "Projelerin kaydedileceği ve açılacağı Drive klasörünün tarayıcıdaki bağlantısı. Bağlantının tamamını yapıştırabilirsiniz; klasör kimliği kendiliğinden ayrılır.",
            ["DriveScriptUrlLabel"] = "Apps Script URL",
            ["DriveScriptUrlHint"] = "mosair adına Drive'a yazan Apps Script web uygulamasının \"/exec\" ile biten adresi. Aşağıdaki adımlarla bir kez kurulur.",
            ["DriveStepsTitle"] = "Kurulum (bir kez)",
            ["DriveSteps"] = "1. \"Script kodunu kopyala\" ile kodu kopyalayın.\n2. script.google.com → Yeni proje → kodu yapıştırıp kaydedin.\n3. Dağıt → Yeni dağıtım → Web uygulaması; Yürüten: Ben, Erişimi olan: Herkes.\n4. İzinleri onaylayın, verilen /exec adresini yukarıya yapıştırın ve \"Bağlantıyı dene\"ye basın.",
            ["DriveCopyScript"] = "Script kodunu kopyala",
            ["DriveTest"] = "Bağlantıyı dene",
            ["DriveScriptCopied"] = "Script kodu panoya kopyalandı.",
            ["DriveTesting"] = "Deneniyor...",
            ["DriveTestOk"] = "Bağlantı tamam: \"{0}\" klasörüne erişiliyor.",
            ["DriveTestFailed"] = "Bağlantı kurulamadı: {0}",
            ["DriveSettingsNote"] = "Bu ayarlar yalnızca bu bilgisayarda saklanır. Script URL'sini bilen herkes bu klasöre proje yazıp okuyabilir; yalnızca güvendiğiniz kişilerle paylaşın.",
            ["DriveSettingsSaved"] = "Drive ayarları kaydedildi",
            ["DriveNotConfigured"] = "Google Drive ayarlanmamış: Drive klasörü bağlantısını ve Script URL'sini girin.",
            ["DriveErrDeploy"] = "Drive script'i beklenen yanıtı vermedi. Script URL'sini ve web uygulaması dağıtımını (Yürüten: Ben, Erişimi olan: Herkes) kontrol edin.",
            ["DriveOpenTitle"] = "Drive'dan Proje Aç",
            ["DriveOpenFolder"] = "\"{0}\" klasöründe {1} proje",
            ["DriveRefresh"] = "Yenile",
            ["DriveShowInBrowser"] = "Drive'da göster",
            ["DriveSearch"] = "Proje ara...",
            ["DriveSortNewest"] = "En yeni üstte",
            ["DriveSortName"] = "Ada göre (A-Z)",
            ["DriveNoMatch"] = "Aramayla eşleşen proje yok.",
            ["DriveOpenEmpty"] = "\"{0}\" klasöründe henüz .mos projesi yok.",
            ["DriveOpenButton"] = "Aç",
            ["DriveNoMosaic"] = "Kaydedilecek mozaik yok. Önce Mos yapın ya da bir proje açın.",
            ["DriveFailed"] = "Drive işlemi başarısız: {0}",
            ["StatusDriveSaving"] = "Drive'a kaydediliyor: {0}...",
            ["StatusDriveSaved"] = "Drive'a kaydedildi: {0}",
            ["StatusDriveListing"] = "Drive klasörü okunuyor...",
            ["StatusDriveDownloading"] = "Drive'dan indiriliyor: {0}...",
            ["MenuCancelWork"] = "İşlemi İptal Et",
            ["MenuScreenshot"] = "Ekran Görüntüsü Al",
            ["TipCancel"] = "Süren işlemi iptal et (Esc)",
            ["StatusCancelling"] = "İptal ediliyor...",
            ["StatusMosCancelled"] = "Mos iptal edildi",
            ["StatusMosCancelledCleared"] = "Mos iptal edildi; yarım kalan mozaik kaldırıldı, görsel yeniden gösteriliyor",
            ["StatusStockFitCancelled"] = "stoğa göre düzeltme iptal edildi, mozaik stoğa bakılmadan bırakıldı",
            ["StatusStockCheckCancelled"] = "Stok Kontrol iptal edildi; tabloya bir şey yazılmadı",
            ["StatusExportCancelled"] = "Dışa aktarma iptal edildi: {0} (yarım dosya silindi)",
            ["StatusScreenshotSaved"] = "Ekran görüntüsü kaydedildi: {0} (mosairEXPORT)",
            ["TipScreenshot"] = "Ekran görüntüsü: görsel alanında şu an görünen kısmı PNG olarak mosairEXPORT klasörüne kaydeder",
            ["ExportJpegTooLarge"] = "JPEG bu boyutta kaydedilemez: görüntü {0} × {1} px, JPEG kenar başına en fazla {2} px destekler. PNG seçin ya da daha düşük bir görüntü kalitesi seçin.",
            ["ExportEstimating"] = "hesaplanıyor…",
            ["ExportChooseQuality"] = "Görüntü kalitesi seçiniz",
            ["ExportDimsPx"] = "{0} × {1} px",
            ["ExportChoiceQuick"] = "{0} · {1} ≈ {2}{3}",
            ["ExportChoiceAs"] = "{0} · JPEG ≈ {1} · PNG ≈ {2}{3}",
            ["ExportChoiceAsPngOnly"] = "{0} · PNG ≈ {1} (bu boyutta JPEG olmaz){2}",
            ["ExportDefaultQuality"] = "(varsayılan)",
            ["ExportJpegFailed"] = "JPEG kaydedilemedi (bellek yetmemiş olabilir). PNG ya da daha düşük bir görüntü kalitesi deneyin.",
            ["ExportJpegMemoryConfirm"] = "Bu boyutta JPEG için yaklaşık {0} bellek gerekiyor; bilgisayarda şu an yaklaşık {1} kullanılabilir. Devam edilirse bilgisayar yavaşlayabilir ya da kayıt başarısız olabilir. PNG neredeyse hiç bellek kullanmaz. Yine de JPEG olarak kaydedilsin mi?",
            ["SizeMB"] = "{0} MB",
            ["SizeKB"] = "{0} KB",
            ["SizeGB"] = "{0} GB",
            ["StatusOpenFailed"] = "Dosya acilamadi",
            ["StatusGeneratingRs"] = "Acildi, tas dokulari yukleniyor...",
            ["StatusOpened"] = "Acildi: {0}",
            ["StatusError"] = "Hata: {0}",
            ["StatusNoColors"] = "Hata: Aktif renk yok!",
            ["StatusStoneUndo"] = "Tas degisikligi geri alindi",
            ["StatusStoneRedo"] = "Tas degisikligi yeniden uygulandi",
            ["StatusPixelEdit"] = "Pixel edit: {0}",
            ["StatusRsBitmapTooLarge"] = "RS bitmap cok buyuk: {0}x{1}",
            ["StatusCatalogSkipped"] = "Renk katalogunda okunamayan satirlar atlandi (colorsBas.txt satir: {0})",
            ["AlertSaveFailed"] = "Proje kaydedilemedi:\n{0}",

            // Dialog titles
            ["DlgSelectImage"] = "Gorsel Sec",
            ["DlgSaveImage"] = "Gorseli Kaydet",
            ["DlgSaveProject"] = "Projeyi Kaydet",
            ["DlgOpenProject"] = "Proje Ac",
            ["DlgExportImage"] = "Gorseli Disa Aktar",
            ["DlgImages"] = "Gorseller",

            // Dimension info
            ["InfoStonesLabel"] = "Taş",
            ["InfoMouldsLabel"] = "Kalıp",
            ["PadTitle"] = "Kalıba tamamlama",
            ["BtnPadding"] = "Kalıp Dolgu",
            ["TipPadding"] = "Açıkken görsel ve mozaik bir üst tam kalıba (26 × 26 taş = 31,2 cm) tamamlanır: sağa ve alta, renkçe görselden en uzak katalog taşı konur. Mos'tan önce görselin kenarında dolgu bu taşın rengiyle görünür, Mos dolguyu bu taşla yapar. Gerçek taş kullanıldığı için dolgu taşları sayıma girer.",
            ["PadRemoved"] = "Kalıp dolgusu kaldırıldı",
            ["PadDone"] = "Kalıba tamamlandı: {0} dolgu taşı ({1})",
            ["PadPreview"] = "Kalıp dolgusu: {0} dolgu taşı ({1}); Mos dolguyu bu taşla yapar",
            ["PadNotNeeded"] = "Boyut zaten tam kalıp; dolgu gerekmiyor",
            ["PadNoStone"] = "Kalıba tamamlanamadı: katalogda dolguya uygun bir taş yok",
            ["PadNoEdit"] = "Dolgu alanı düzenlenemez",

            // Properties format
            ["PropStoneFmt"] = "Taş #{0}",
            ["PropEditedFmt"] = "Düzenlenen: {0}",

            // Alert dialogs
            ["AlertExportTitle"] = "Disa Aktarma",
            ["AlertExportNoMosaic"] = "Disa aktarilacak mozaik yok.\nOnce bir gorsel yukleyin ve mozaiklestirme yapin.",
            ["ExportChoiceImage"] = "Görsel: {0} × {1} px (Mos'tan önce; Kalıp Dolgu açıksa dolgusuyla)",
            ["AlertMosaicTitle"] = "Mozaiklestirme",
            ["AlertMosaicNoImage"] = "Gorsel yuklenmeden mozaiklestirme yapilamaz.\nOnce bir gorsel yukleyin.",
            ["AlertMosaicNoColors"] = "Aktif renk yok!\nEn az bir renk secili olmalidir.",
            ["AlertProjectTitle"] = "Proje",
            ["AlertProjectOpenFailed"] = "Proje dosyasi acilamadi.\nDosya bozuk veya uyumsuz olabilir. Eski WPF surumuyle (binary) kaydedilmis projeleri once guncel WPF'te acip yeniden kaydedin.",
            ["AlertMemoryTitle"] = "Bellek Yetersiz",
            ["AlertMemoryBody"] = "Islem icin yeterli bellek yok.\ncm degerini kucultun.",
            ["AlertErrorTitle"] = "Hata",
            ["AlertErrorBody"] = "Beklenmeyen bir hata olustu:\n{0}",
            ["AlertImageTitle"] = "Gorsel Yukleme",
            ["AlertImageFailed"] = "Gorsel yuklenemedi.\nDosya formati desteklenmiyor veya dosya bozuk olabilir.",
            ["AlertResolutionTitle"] = "Cozunurluk Yetersiz",
            ["AlertResolutionBody"] = "Yuklenen gorselin cozunurlugu, istenen mozaik boyutu icin yeterli degildir.\nDaha yuksek cozunurluklu bir gorsel yukleyiniz.",
        };

        // ─── ENGLISH ───
        private static readonly Dictionary<string, string> En = new()
        {
            // Menu
            ["MenuFile"] = "File",
            ["MenuLoadImage"] = "Load Image",
            ["MenuOpenProject"] = "Open Project",
            ["MenuSave"] = "Save Project",
            ["MenuSaveAs"] = "Save Project As",
            ["MenuExport"] = "mosairEXPORT",
            ["MenuExportAs"] = "mosairEXPORT As",
            ["MenuEdit"] = "Edit",
            ["MenuSelectAll"] = "Select All Colors",
            ["MenuDeselectAll"] = "Deselect All Colors",
            ["MenuView"] = "View",
            ["MenuFitToScreen"] = "Fit to Screen",
            ["MenuPropertiesPanel"] = "Properties Panel",
            ["MenuAdjustPanel"] = "Image Adjustments",
            ["AdjTitle"] = "IMAGE ADJUSTMENTS",
            ["AdjTabLight"] = "Light",
            ["AdjTabColor"] = "Hue/Saturation",
            ["AdjLiveMos"] = "Live Mos",
            ["TipAdjLiveMos"] = "When on, every adjustment is followed by a Mos and the mosaic updates at once. When off, a change shows the adjusted image; press Mos for the mosaic.",
            ["AdjExposure"] = "Exposure",
            ["AdjHighlights"] = "Highlights",
            ["AdjShadows"] = "Shadows",
            ["AdjWhites"] = "Whites",
            ["AdjBlacks"] = "Blacks",
            ["AdjHue"] = "Hue",
            ["AdjLightness"] = "Lightness",
            ["AdjColorize"] = "Colorize",
            ["TipAdjColorize"] = "Tints the whole image in one hue; Hue, Saturation and Lightness set that hue.",
            ["AdjRange0"] = "Master (all colours)",
            ["AdjRange1"] = "Reds",
            ["AdjRange2"] = "Yellows",
            ["AdjRange3"] = "Greens",
            ["AdjRange4"] = "Cyans",
            ["AdjRange5"] = "Blues",
            ["AdjRange6"] = "Magentas",
            ["AdjHint"] = "Right-click: reset · Shift + drag: fine · Wheel: ±1 · Number box: Enter",
            ["AdjBrightness"] = "Brightness",
            ["AdjContrast"] = "Contrast",
            ["AdjSaturation"] = "Saturation",
            ["AdjGamma"] = "Gamma",
            ["AdjReset"] = "Reset",
            ["AdjNeedsMos"] = "Image adjustments changed; press Mos to update the mosaic.",
            ["TipAdjust"] = "Brightness, contrast, saturation and gamma of the loaded image. Mos uses the adjusted image; the file itself is not changed, the settings are saved with the project.",
            ["TipAdjSlider"] = "Right-click to reset",
            ["TipAdjustShow"] = "Show the image adjustments",
            ["MenuSmoothMouse"] = "Smooth Mouse Motion",
            ["MenuTheme"] = "Theme",
            ["MenuLightTheme"] = "Light Theme",
            ["ThemeLapis"] = "Lapis",
            ["ThemePastel"] = "Sage and Lavender",
            ["ThemeGraphite"] = "Graphite and Teal",
            ["ThemeTravertine"] = "Travertine",
            ["ThemeInk"] = "Ink and Lilac",
            ["MenuWatchImages"] = "Notify New Images",
            ["ToastNewDownload"] = "NEW IMAGE IN DOWNLOADS",
            ["ToastNewDesktop"] = "NEW IMAGE ON THE DESKTOP",
            ["ToastQuestion"] = "Open it in mosair?",
            ["ToastExported"] = "EXPORTED",
            ["ToastScreenshotSaved"] = "SCREENSHOT SAVED",
            ["ToastProjectSaved"] = "PROJECT SAVED",
            ["ToastOpenFile"] = "Open",
            ["ToastShowFolder"] = "Show in folder",
            ["ToastOpen"] = "Open",
            ["ToastDismiss"] = "Dismiss",
            ["ToastSeconds"] = "{0} s",
            ["StatusToastBusy"] = "A job is running; you can open it when it ends.",
            ["StatusSavingProject"] = "Saving project: {0}",
            ["StatusOpeningProject"] = "Opening project: {0}",
            ["MenuTools"] = "Tools",
            ["MenuMosaicize"] = "Mosaicize",
            ["MenuPixelEdit"] = "Pixel Edit",
            ["MenuShowGrid"] = "Show Grid",
            ["MenuGridColor"] = "Grid Color",
            ["MenuInterp"] = "Interpolation Method",
            ["MenuOptimum"] = "Optimum Stone Count",
            ["MenuStoneCount"] = "Stone Count",
            ["MenuStonesSuggested"] = "Back to Suggested",
            ["MenuStonesMore"] = "One More Stone",
            ["MenuStonesLess"] = "One Fewer Stone",
            ["MenuStock"] = "Stock",
            ["MenuStockOpen"] = "Open Stock Sheet",
            ["MenuStockFetch"] = "Fetch Stock",
            ["MenuStockCheck"] = "Check Stock",
            ["MenuStockAdd"] = "Add Stock",
            ["MenuHelp"] = "Help",
            ["MenuUserGuide"] = "User Guide",

            // Toolbar tooltips
            ["TipLoadImage"] = "Load Image",
            ["TipOpenProject"] = "Open Project (.mos)",
            ["TipSave"] = "Save Project",
            ["TipMosaicize"] = "Mosaicize",
            ["TipPixelEdit"] = "Edit Pixel (Middle Click)\n1) Select source color\n2) Apply to target pixel",
            ["TipSaveAs"] = "Save Project As",
            ["TipExport"] = "Export: mosairEXPORT / mosairEXPORT As, choosing the image quality (with file sizes). Right-click: open the folder",
            ["TipFit"] = "Fit to Screen",
            ["TipGrid"] = "Show/Hide Grid",
            ["TipInterp"] = "Interpolation Method",
            ["TipLanguage"] = "Language",
            ["TipTheme"] = "Toggle Theme",

            // Buttons
            ["BtnSelectAll"] = "Select All Colors",
            ["BtnDeselectAll"] = "Deselect All Colors",

            // Column headers
            ["ColCatalog"] = "Catalog Color",
            ["ColMatch"] = "Match",
            ["ColAssigned"] = "Assigned Color",

            // Left panel
            ["LblGrid"] = "Grid",
            ["LblGridColor"] = "Grid Color",
            ["LblInterp"] = "Interp",
            ["LblOptimum"] = "Optimum",
            ["TipOptimum"] = "Find the optimum stone count automatically",
            ["TipOptimalSlider"] = "Number of stone colours (right-click: the suggested count)",

            // Google Sheet stock
            ["TipStockSheet"] = "Open the stock sheet in the browser (arrow next to it: open sheet / stock sheet settings)",
            ["TipStockSheetMenu"] = "Stock sheet: open or set up",
            ["TipStockFetch"] = "Fetch stock: read stock from the Google Sheet and disable stones that ran out (arrow next to it: only mark them red)",
            ["TipStockFetchMenu"] = "Fetch stock options",
            ["MenuStockFetchDisable"] = "Disable stones with no stock",
            ["MenuStockFetchMark"] = "Mark stones with no stock in red",
            ["TipStockCheck"] = "Check stock: write this mosaic's stone counts to the sheet and mark stones that fall short",
            ["TipStockClear"] = "Clear stock: clear this mosaic's column (right-click: all mosaic columns)",
            ["TipStockAdd"] = "Add stock: move Estimated Remaining into On Hand and clear the mosaic columns",
            ["MenuStockSettings"] = "Stock Settings...",
            ["MenuStockClearOne"] = "Clear this mosaic's column",
            ["MenuStockClearAll"] = "Clear all mosaic columns",
            ["StockTitle"] = "Stock",
            ["StockNotConfigured"] = "The stock sheet is not set up. Open Stock Settings from the arrow next to the sheet button (or right-click it) and enter the Sheet ID and Script URL.",
            ["StockErrFmt"] = "Stock action failed:\n{0}",
            ["StockErrColumns"] = "Column '{0}' not found. Headers found: {1}",
            ["StockErrEmpty"] = "The sheet came back empty.",
            ["StockErrDeploy"] = "Script URL is invalid or the deployment is misconfigured. Apps Script → Manage deployments → Access must be Anyone.",
            ["StockNoProject"] = "No project name found. Load an image first.",
            ["StockNoMosaic"] = "No stone data. Run Mos first.",
            ["StockFetched"] = "Stock fetched: {0} stones read, {1} stones disabled",
            ["StockFetchedMarked"] = "Stock fetched: {0} stones read, {1} have no stock (red dot, selection unchanged)",
            ["StockLoadedOnStart"] = "Stock loaded: {0} stones (kg in the catalog tooltip)",
            ["StockLoadOnStartFailed"] = "Stock could not be loaded: {0}",
            ["StockCheckOk"] = "Stock check ({0}): enough stock for every stone",
            ["StockCheckShort"] = "Stock check ({0}): {1} stones are short (red dot)",
            ["StockKgLeft"] = "left",
            ["LblStockAware"] = "By stock",
            ["MenuStockAware"] = "Fit to Stock",
            ["TipStockAware"] = "By stock: when on, Mos (Optimum or normal) uses only stones that are in stock. A stone without enough stock is used as far as it goes and the rest is filled with the closest-coloured stone in stock. Stock is read from the sheet when the app starts and whenever an image or project is loaded: Bizdeki (kg) minus what other mosaics set aside. 1 stone = 3.3 g. Check Stock writes the final counts to the sheet.",
            ["StockAwareNoStock"] = "Stock could not be read from the sheet; Mos was made without it.",
            ["StockAwareTitle"] = "By Stock",
            ["StockAwareEditsConfirm"] = "Fitting to stock will discard {0} pixel edits. Continue?",
            ["StockAwareWritten"] = "corrected counts written to the sheet",
            ["StockCountsWritten"] = "counts written to the sheet",
            ["StockAwareRecheck"] = "stone count changed, run Check Stock again for the sheet",
            ["StockAwareSmall"] = "Dropped for being used fewer than {0} times: {1}",
            ["StockAwareReadFailed"] = "Stock could not be read; no stock fix was made: {0}",
            ["StockAwareNeedsMos"] = "To fit to stock, run Mos on this image first (it does not work on opened projects).",
            ["StockAwareCannotFix"] = "Some pixels could not be matched to one catalog stone for certain (a colour outside the catalog, or two stones with the same colour), so no stock fix was made.",
            ["StockAwareOk"] = "Stock is enough, mosaic unchanged",
            ["StockAwareChanged"] = "By stock: {1} stones of {0} stone types moved",
            ["StockAwareMove"] = "{0} → {1}: {2} stones ({3} kg)",
            ["StockAwareAdded"] = "New stone types added: {0}",
            ["StockAwareLevel1"] = "Similar stones did not have enough stock, so the similarity limit was doubled.",
            ["StockAwareLevel2"] = "Similar stones did not have enough stock, so the similarity limit was quadrupled.",
            ["StockAwareLevel3"] = "Similar stones did not have enough stock, so any stone with stock was used.",
            ["StockAwareLevel4"] = "Stock was met by going over the limit of new stone types.",
            ["StockAwareShort"] = "Still not enough stock: {0}",
            ["StockAwareUnknown"] = "Stones without a stock row in the sheet, not checked: {0}",
            ["StockAwareShortCount"] = "{0} stone types still short",
            ["StockAwareUnknownCount"] = "{0} stone types not in the sheet",
            ["StockAwareSeeWindow"] = "details in the window",
            ["StockAwareSeeTooltip"] = "details in the By stock tooltip",
            ["StockClearTitle"] = "Clear Stock",
            ["StockClearOneConfirm"] = "The column for mosaic '{0}' will be cleared and its header reset to mosaicX.\n\nAre you sure?",
            ["StockClearedOne"] = "Column '{0}' cleared",
            ["StockClearAllTitle"] = "Clear All",
            ["StockClearAllConfirm"] = "All mosaic columns will be cleared and their headers reset.\n\nAre you sure?",
            ["StockClearedAll"] = "All mosaic columns cleared",
            ["StockAddTitle"] = "Add Stock",
            ["StockAddConfirm"] = "Estimated Remaining values will be moved into On Hand, then all mosaic columns will be cleared.\n\nAre you sure?",
            ["StockAdded"] = "Stock added",
            ["StockSettingsTitle"] = "Stock Sheet Settings",
            ["StockSheetIdLabel"] = "Google Sheet ID",
            ["StockScriptUrlLabel"] = "Apps Script URL",
            ["StockSheetIdHint"] = "Open the stock sheet in your browser; the Sheet ID is the part of the link between /d/ and /edit. You can also paste the whole link; the ID is extracted when you save. Fetch Stock and Check Stock read this sheet.",
            ["StockScriptUrlHint"] = "In the sheet, open Extensions → Apps Script, then go to Deploy → Manage deployments and copy the Web app URL. It must end with /exec. Check Stock, Clear Stock and Add Stock write to the sheet through this address.",
            ["StockRequirementsTitle"] = "Requirements",
            ["StockRequirements"] = "• The sheet must be shared with \"Anyone with the link\" with at least Viewer access.\n• The first row must have columns titled mos, Bizdeki (kg) and Tahmini Kalan.\n• The web app must be deployed with \"Who has access: Anyone\". The script must already be installed in the sheet; this is usually done by the sheet owner.\n• To try actions that change the sheet, work on a copy of the sheet first.",
            ["StockSettingsNote"] = "These values are stored only on this computer. Anyone with the Script URL can write to the sheet; share it only with people you trust.",
            ["StockSettingsSaved"] = "Stock settings saved",
            ["DlgYes"] = "Yes",
            ["DlgNo"] = "No",
            ["DlgSave"] = "Save",
            ["DlgCancel"] = "Cancel",

            // Properties
            ["PropTitle"] = "Properties",
            ["PropColor"] = "COLOR",
            ["PropTexture"] = "TEXTURE",
            ["PropVariants"] = "VARIANTS",
            ["PropRgb"] = "RGB",
            ["PropCoordinate"] = "COORDINATE",
            ["PropPixel"] = "Pixel",
            ["PropMold"] = "Mold",
            ["PropEditing"] = "EDITING",
            ["PropImage"] = "IMAGE",
            ["PropDetails"] = "DETAILS",
            ["PropResolution"] = "Resolution",
            ["PropMegapixels"] = "Megapixels",
            ["PropAspect"] = "Aspect ratio",
            ["PropFileSize"] = "File size",
            ["PropModified"] = "Modified",
            ["PropStoneHint"] = "Click a stone in the mosaic to see its details.",
            ["PropNoImage"] = "The image's details appear here once an image is loaded.",
            ["PropImageMissing"] = "Image file not found",
            ["TipPanelHide"] = "Hide panel (F4)",
            ["TipPanelShow"] = "Show the properties panel (F4)",
            ["TipClearSelection"] = "Back to the image details",
            ["PropUndoRedo"] = $"{Mod}+Z Undo  {Mod}+Y Redo",

            // Warning
            ["WarnOk"] = "OK",

            // Status (format strings)
            ["StatusReady"] = "Ready",
            ["StatusImageLoaded"] = "Image loaded",
            ["StatusStarting"] = "Starting mosaic...",
            ["StatusActiveColors"] = "Active colors: {0}/{1}",
            ["StatusCalculated"] = "rgbM={0} calculated, processing...",
            ["StatusCompleted"] = "Completed — {0} colors, {1}s",
            ["StatusUsedColors"] = "{1} of {0} colors used",
            ["StatusSaved"] = "Saved: {0}",
            ["StatusExporting"] = "Exporting: {0}...",
            ["StatusExportingPct"] = "Exporting: {0} — {1}%",
            ["BtnCancel"] = "Cancel",
            ["MenuDrive"] = "Google Drive",
            ["MenuDriveSave"] = "Save to Drive",
            ["MenuDriveOpen"] = "Open from Drive...",
            ["MenuDriveSettings"] = "Drive Folder Settings...",
            ["TipDrive"] = "Google Drive: save the project to the Drive folder (arrow: open from Drive, folder settings)",
            ["AlertDriveTitle"] = "Google Drive",
            ["DriveSettingsTitle"] = "Google Drive Settings",
            ["DriveFolderLabel"] = "Drive folder link",
            ["DriveFolderHint"] = "The browser link of the Drive folder where projects are saved and opened. You can paste the whole link; the folder ID is taken from it.",
            ["DriveScriptUrlLabel"] = "Apps Script URL",
            ["DriveScriptUrlHint"] = "The address ending in \"/exec\" of the Apps Script web app that writes to Drive for mosair. It is set up once with the steps below.",
            ["DriveStepsTitle"] = "Setup (once)",
            ["DriveSteps"] = "1. Copy the code with \"Copy script code\".\n2. script.google.com → New project → paste the code and save.\n3. Deploy → New deployment → Web app; Execute as: Me, Who has access: Anyone.\n4. Approve the permissions, paste the /exec address above and press \"Test connection\".",
            ["DriveCopyScript"] = "Copy script code",
            ["DriveTest"] = "Test connection",
            ["DriveScriptCopied"] = "Script code copied to the clipboard.",
            ["DriveTesting"] = "Testing...",
            ["DriveTestOk"] = "Connection OK: the folder \"{0}\" is reachable.",
            ["DriveTestFailed"] = "Could not connect: {0}",
            ["DriveSettingsNote"] = "These settings are stored on this computer only. Anyone with the script URL can write projects to and read them from this folder; share it only with people you trust.",
            ["DriveSettingsSaved"] = "Drive settings saved",
            ["DriveNotConfigured"] = "Google Drive is not set up: enter the Drive folder link and the script URL.",
            ["DriveErrDeploy"] = "The Drive script did not answer as expected. Check the script URL and the web app deployment (Execute as: Me, Who has access: Anyone).",
            ["DriveOpenTitle"] = "Open Project from Drive",
            ["DriveOpenFolder"] = "{1} projects in \"{0}\"",
            ["DriveRefresh"] = "Refresh",
            ["DriveShowInBrowser"] = "Show in Drive",
            ["DriveSearch"] = "Search projects...",
            ["DriveSortNewest"] = "Newest first",
            ["DriveSortName"] = "By name (A-Z)",
            ["DriveNoMatch"] = "No project matches the search.",
            ["DriveOpenEmpty"] = "There are no .mos projects in \"{0}\" yet.",
            ["DriveOpenButton"] = "Open",
            ["DriveNoMosaic"] = "There is no mosaic to save. Run Mos or open a project first.",
            ["DriveFailed"] = "Drive action failed: {0}",
            ["StatusDriveSaving"] = "Saving to Drive: {0}...",
            ["StatusDriveSaved"] = "Saved to Drive: {0}",
            ["StatusDriveListing"] = "Reading the Drive folder...",
            ["StatusDriveDownloading"] = "Downloading from Drive: {0}...",
            ["MenuCancelWork"] = "Cancel Running Job",
            ["MenuScreenshot"] = "Take Screenshot",
            ["TipCancel"] = "Cancel the running job (Esc)",
            ["StatusCancelling"] = "Cancelling...",
            ["StatusMosCancelled"] = "Mos cancelled",
            ["StatusMosCancelledCleared"] = "Mos cancelled; the half-built mosaic was removed and the image is shown again",
            ["StatusStockFitCancelled"] = "stock fit cancelled, the mosaic was left without it",
            ["StatusStockCheckCancelled"] = "Check Stock cancelled; nothing was written to the sheet",
            ["StatusExportCancelled"] = "Export cancelled: {0} (the partial file was deleted)",
            ["StatusScreenshotSaved"] = "Screenshot saved: {0} (mosairEXPORT)",
            ["TipScreenshot"] = "Screenshot: saves what the image area shows right now as a PNG in the mosairEXPORT folder",
            ["ExportJpegTooLarge"] = "JPEG cannot be saved at this size: the image is {0} × {1} px and JPEG allows at most {2} px a side. Choose PNG or a lower image quality.",
            ["ExportEstimating"] = "estimating…",
            ["ExportChooseQuality"] = "Choose image quality",
            ["ExportDimsPx"] = "{0} × {1} px",
            ["ExportChoiceQuick"] = "{0} · {1} ≈ {2}{3}",
            ["ExportChoiceAs"] = "{0} · JPEG ≈ {1} · PNG ≈ {2}{3}",
            ["ExportChoiceAsPngOnly"] = "{0} · PNG ≈ {1} (no JPEG at this size){2}",
            ["ExportDefaultQuality"] = "(default)",
            ["ExportJpegFailed"] = "The JPEG could not be saved (possibly not enough memory). Try PNG or a lower image quality.",
            ["ExportJpegMemoryConfirm"] = "A JPEG of this size needs about {0} of memory; about {1} is available now. Going on may slow the computer down or fail. PNG needs almost no memory. Save as JPEG anyway?",
            ["SizeMB"] = "{0} MB",
            ["SizeKB"] = "{0} KB",
            ["SizeGB"] = "{0} GB",
            ["StatusOpenFailed"] = "File could not be opened",
            ["StatusGeneratingRs"] = "Opened, loading stone textures...",
            ["StatusOpened"] = "Opened: {0}",
            ["StatusError"] = "Error: {0}",
            ["StatusNoColors"] = "Error: No active colors!",
            ["StatusStoneUndo"] = "Stone change undone",
            ["StatusStoneRedo"] = "Stone change reapplied",
            ["StatusPixelEdit"] = "Pixel edit: {0}",
            ["StatusRsBitmapTooLarge"] = "RS bitmap too large: {0}x{1}",
            ["StatusCatalogSkipped"] = "Unreadable color catalog lines were skipped (colorsBas.txt line: {0})",
            ["AlertSaveFailed"] = "The project could not be saved:\n{0}",

            // Dialog titles
            ["DlgSelectImage"] = "Select Image",
            ["DlgSaveImage"] = "Save Image",
            ["DlgSaveProject"] = "Save Project",
            ["DlgOpenProject"] = "Open Project",
            ["DlgExportImage"] = "Export Image",
            ["DlgImages"] = "Images",

            // Dimension info
            ["InfoStonesLabel"] = "Stones",
            ["InfoMouldsLabel"] = "Moulds",
            ["PadTitle"] = "Whole moulds",
            ["BtnPadding"] = "Mould Fill",
            ["TipPadding"] = "When on, the image and the mosaic are filled up to the next whole mould (26 × 26 stones = 31.2 cm): on the right and at the bottom with the catalog stone farthest in colour from the image. Before Mos the padding shows around the image in that stone's colour, and Mos fills it with that stone. These are real stones, so they are counted.",
            ["PadRemoved"] = "Mould fill removed",
            ["PadDone"] = "Filled to whole moulds: {0} filler stones ({1})",
            ["PadPreview"] = "Mould fill: {0} filler stones ({1}); Mos fills with this stone",
            ["PadNotNeeded"] = "The size is already whole moulds; no padding needed",
            ["PadNoStone"] = "Not filled to whole moulds: the catalog has no stone for the padding",
            ["PadNoEdit"] = "The padding cannot be edited",

            // Properties format
            ["PropStoneFmt"] = "Stone #{0}",
            ["PropEditedFmt"] = "Edited: {0}",

            // Alert dialogs
            ["AlertExportTitle"] = "Export",
            ["AlertExportNoMosaic"] = "No mosaic to export.\nLoad an image and run mosaicize first.",
            ["ExportChoiceImage"] = "Image: {0} × {1} px (before Mos; with its padding when Mould Fill is on)",
            ["AlertMosaicTitle"] = "Mosaicize",
            ["AlertMosaicNoImage"] = "Cannot mosaicize without an image.\nLoad an image first.",
            ["AlertMosaicNoColors"] = "No active colors!\nAt least one color must be selected.",
            ["AlertProjectTitle"] = "Project",
            ["AlertProjectOpenFailed"] = "Could not open project file.\nThe file may be corrupted or incompatible. Projects saved by an older WPF version (binary) must first be opened and saved again in the current WPF.",
            ["AlertMemoryTitle"] = "Insufficient Memory",
            ["AlertMemoryBody"] = "Not enough memory for this operation.\nReduce the cm value.",
            ["AlertErrorTitle"] = "Error",
            ["AlertErrorBody"] = "An unexpected error occurred:\n{0}",
            ["AlertImageTitle"] = "Image Loading",
            ["AlertImageFailed"] = "Could not load image.\nThe file format may be unsupported or the file may be corrupted.",
            ["AlertResolutionTitle"] = "Insufficient Resolution",
            ["AlertResolutionBody"] = "The resolution of the uploaded image is not sufficient for the requested mosaic size.\nPlease upload a higher resolution image.",
        };
    }
}
